### ISSUE TITLE
no support for wave_format_extensible (0xfffe)

### ISSUE THREAD

**Issue by multi-io** [jstrait/wavefile#11]
When trying to read a wav file with WAVEFORMATEX encoding (format code 0xfffe/65534), wavefile bails out with:

```
Audio format is 65534, but only format code 1 (PCM) or 3 (floating point) is supported. (WaveFile::UnsupportedFormatError)
```

**Comment by jstrait** [comment]
@multi-io v0.8.0 of this gem was released today, and includes support for reading Wave files using WAVEFORMATEXTENSIBLE.

However, here are some notes/limitations about the current implementation:

* The same formats supported in "vanilla" Wave files are supported when reading WAVEFORMATEXTENSIBLE files. That is, PCM (8/16/24/32 bits per sample) or IEEE_FLOAT (32/64 bits per sample).
* The channel speaker mapping field is not exposed.
* The number of valid bits per sample must match the sample container size. For example, if a file has a sample container size of 24 bits and each sample is 24 bits, then it can be read. If the container size is 32 bits and each sample is 24 bits, it can't be read.
* Writing files using WAVEFORMATEXTENSIBLE format is not supported - all files will be written as a "vanilla" file regardless of the number of channels or sample format.

Since this feature has been implemented, closing this issue - thanks for opening it!
