### ISSUE TITLE
Bufer from bytes & mulaw

### ISSUE THREAD

**Issue by Ammet** [jstrait/wavefile#35]
Hi. I am receiving bytes for the linear16 wav file.
Can I somehow format it to mulaw/8000 without creating or saving a file?
And if not, is this format change possible at all?

**Comment by jstrait** [comment]
@Ammet Unfortunately, the WaveFile gem currently does not support mu-law format (either reading or writing).

I have personally never worked with mu-law format before, but my general understanding is that it is possible to convert PCM sample data to mu-law using the appropriate algorithm. However, you would need to do that work manually, due to the gem lacking support for this.

**Comment by Ammet** [comment]
Got it. Thank you
